// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwn31EBIjM2-6OMu6s0cEC4ZuJdQ3CQbU',
    appId: '1:343354938486:web:3a05e21869875b8a37fb57',
    messagingSenderId: '343354938486',
    projectId: 'flutter-chatapp-d0d15',
    authDomain: 'flutter-chatapp-d0d15.firebaseapp.com',
    storageBucket: 'flutter-chatapp-d0d15.appspot.com',
    measurementId: 'G-2P4WVQRCPQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDieQTAQNWy1PooIBTXLPzYhl5V7xe-X5s',
    appId: '1:343354938486:android:6654598ac1ae23be37fb57',
    messagingSenderId: '343354938486',
    projectId: 'flutter-chatapp-d0d15',
    storageBucket: 'flutter-chatapp-d0d15.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO6-GNs9dSvJXANdwXcEHW30g3nNuf2cc',
    appId: '1:343354938486:ios:d5ddf16df72beff737fb57',
    messagingSenderId: '343354938486',
    projectId: 'flutter-chatapp-d0d15',
    storageBucket: 'flutter-chatapp-d0d15.appspot.com',
    iosClientId: '343354938486-p01stor6lf1kqf0v9e4e9fhnmbvj6m73.apps.googleusercontent.com',
    iosBundleId: 'com.example.helloWorldFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAO6-GNs9dSvJXANdwXcEHW30g3nNuf2cc',
    appId: '1:343354938486:ios:e6d20e5ccde741f837fb57',
    messagingSenderId: '343354938486',
    projectId: 'flutter-chatapp-d0d15',
    storageBucket: 'flutter-chatapp-d0d15.appspot.com',
    iosClientId: '343354938486-6hecsusoqsg3tmcd26cbcvrrv9lqc4r5.apps.googleusercontent.com',
    iosBundleId: 'com.example.helloWorldFlutter.RunnerTests',
  );
}
